# Generated by Django 6.0.4 on 2026-05-03 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assembly', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(choices=[('manufacturing', 'Defeito de Fabricação'), ('assembly', 'Problema de Montagem'), ('other', 'Outro')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='defects/%Y/%m/')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_description', models.TextField(blank=True)),
                ('resolution_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_defects', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_defects', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='assembly.assemblysession')),
                ('step_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='assembly.stepexecution')),
            ],
            options={
                'verbose_name': 'Defeito / Problema',
                'verbose_name_plural': 'Defeitos / Problemas',
                'ordering': ['-reported_at'],
            },
        ),
    ]
