# Generated by Django 6.0.4 on 2026-05-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defect',
            options={'ordering': ['-reported_at'], 'verbose_name': 'Defect', 'verbose_name_plural': 'Defects'},
        ),
        migrations.AddField(
            model_name='defect',
            name='step_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Related Step / Note'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='defect_type',
            field=models.CharField(choices=[('manufacturing', 'Manufacturing Defect'), ('assembly', 'Assembly Issue'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='defect',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
    ]
