# Generated by Django 6.0.4 on 2026-05-06 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_alter_assemblyprocess_options_and_more'),
        ('defects', '0005_populate_defect_components'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['reported_at'], name='defects_def_reporte_52cc78_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['resolved_at'], name='defects_def_resolve_1135d2_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['severity'], name='defects_def_severit_b19dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['component'], name='defects_def_compone_a6eb7c_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['session', 'resolved_at'], name='defects_def_session_15a619_idx'),
        ),
    ]
