# Generated by Django 6.0.4 on 2026-05-03 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modelo de Bike',
                'verbose_name_plural': 'Modelos de Bike',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('frame', 'Quadro'), ('motor', 'Motor'), ('battery', 'Bateria'), ('brakes', 'Freios'), ('transmission', 'Transmissão'), ('wheels', 'Rodas'), ('electronics', 'Eletrônicos'), ('other', 'Outros')], default='other', max_length=30)),
                ('part_number', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('bike_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bikes.bikemodel')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['category', 'name'],
            },
        ),
    ]
