# Generated by Django 6.0.4 on 2026-05-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikemodel',
            options={'ordering': ['brand', 'name'], 'verbose_name': 'Bike Model', 'verbose_name_plural': 'Bike Models'},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('frame', 'Frame'), ('motor', 'Motor'), ('battery', 'Battery'), ('brakes', 'Brakes'), ('transmission', 'Transmission'), ('wheels', 'Wheels'), ('electronics', 'Electronics'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
