# Generated by Django 6.0.4 on 2026-05-03 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='bikes.bikemodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo de Montagem',
                'verbose_name_plural': 'Processos de Montagem',
            },
        ),
        migrations.CreateModel(
            name='AssemblySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('paused', 'Pausada')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('bike_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bikes.bikemodel')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assembly.assemblyprocess')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Montagem',
                'verbose_name_plural': 'Sessões de Montagem',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('estimated_minutes', models.PositiveIntegerField(default=0)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='assembly.assemblyprocess')),
            ],
            options={
                'verbose_name': 'Etapa de Montagem',
                'verbose_name_plural': 'Etapas de Montagem',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actual_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='assembly.assemblysession')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assembly.assemblystep')),
            ],
            options={
                'verbose_name': 'Execução de Etapa',
                'verbose_name_plural': 'Execuções de Etapa',
                'ordering': ['step__order'],
            },
        ),
    ]
