# Generated by Django 6.0.4 on 2026-05-06 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_add_order_number'),
        ('bikes', '0002_alter_bikemodel_options_alter_component_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblyprocess',
            options={'verbose_name': 'Assembly Process', 'verbose_name_plural': 'Assembly Processes'},
        ),
        migrations.AlterModelOptions(
            name='assemblysession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Assembly Session', 'verbose_name_plural': 'Assembly Sessions'},
        ),
        migrations.AlterModelOptions(
            name='assemblystep',
            options={'ordering': ['order'], 'verbose_name': 'Assembly Step', 'verbose_name_plural': 'Assembly Steps'},
        ),
        migrations.AlterModelOptions(
            name='stepexecution',
            options={'ordering': ['step__order'], 'verbose_name': 'Step Execution', 'verbose_name_plural': 'Step Executions'},
        ),
        migrations.AlterField(
            model_name='assemblysession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='in_progress', max_length=20),
        ),
        migrations.AddIndex(
            model_name='assemblysession',
            index=models.Index(fields=['status'], name='assembly_as_status_0326c6_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblysession',
            index=models.Index(fields=['started_at'], name='assembly_as_started_63c2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblysession',
            index=models.Index(fields=['finished_at'], name='assembly_as_finishe_c6d68b_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblysession',
            index=models.Index(fields=['worker', 'status'], name='assembly_as_worker__60f4fc_idx'),
        ),
    ]
