# Generated by Django 6.0.4 on 2026-05-07 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_alter_assemblyprocess_options_and_more'),
        ('bikes', '0002_alter_bikemodel_options_alter_component_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveIntegerField()),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Order Unit',
                'verbose_name_plural': 'Order Units',
                'ordering': ['unit_number'],
            },
        ),
        migrations.AddField(
            model_name='assemblysession',
            name='order_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='assembly.orderunit'),
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Order Number')),
                ('quantity', models.PositiveIntegerField(verbose_name='Total Units')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Target Date')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='bikes.bikemodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderunit',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='assembly.productionorder'),
        ),
        migrations.AlterUniqueTogether(
            name='orderunit',
            unique_together={('order', 'unit_number')},
        ),
    ]
