# Generated by Django 6.0.4 on 2026-05-12 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0004_orderunit_assemblysession_order_unit_productionorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stepexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='stepexecution',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='assigned_steps', to=settings.AUTH_USER_MODEL),
        ),
    ]
